server:
  port: 7075

spring:
  application:
    name: menu-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/spring_menus_hrms
    username: postgres
    password: root
    initialization-mode: always